* ChangeLog
** 0.2.x (complete re-write)
*** 0.2.0-alpha5

More minor bugfixes as a result of using Flow in other projects

*** 0.2.0-alpha4

Minor typo. :(

*** 0.2.0-alpha3

Minor bugfix - lens atoms weren't being updated when their parent
atoms changed.

*** 0.2.0-alpha2

Added:
- Read-Write support for lenses
- Batching of updates
- Using =requestAnimationFrame= if available

Still to do:

- Docs
- Sample apps
- Even more copious testing

*** 0.2.0-alpha1

Complete re-write of the Flow library (it's probably best thought of
as a different library tbh!)

Flow is now a compiled DSL - the compiler analyses all of the
dependencies at compile-time, and only updates what is necessary at
run-time. The new DSL is a lot more expressive than the old =let<<= /
=for<<= combination.

Still missing before I can go to 0.2.0:

- Updated docs
- Updating sample apps
- Currently only read-only wrapped lenses
- Copious testing

A big thanks to [[https://github.com/lsnape][Luke Snape]] for all his help in design/implementation
discussions - it really helped in getting my head around all of this!

** 0.1.0

Initial release - thanks to [[https://github.com/henrygarner][Henry Garner]], [[https://github.com/matlux][Mathieu Gauthron]], [[https://github.com/n8dawgrr][Nathan
Matthews]] and [[https://github.com/malcolmsparks][Malcolm Sparks]], whose advice and feedback made it happen.
